version: '3'

services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        environment:
            SYSTEM_IP: 0.0.0.0
            SYSTEM_PORT: 5000
            SYSTEM_AUTH_KEY: secretkey
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: password
            DB_NAME: todo_database
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

volumes:
    postgresql:
    postgresql_data: