version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: todo_database
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        environment:
            SYSTEM_IP: 0.0.0.0
            SYSTEM_PORT: 5000
            SYSTEM_AUTH_KEY: secretkey
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: password
            DB_NAME: todo_database
        depends_on:
            - db
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
            - backend
volumes:
    postgresql:
    postgresql_data: