version: '3'

services:
    web:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        links:
            - db:todolist-link
        volumes:
            - ./env.ini:/go/app/env.ini
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

volumes:
    postgresql:
    postgresql_data: