apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: zondayang/todolist_backend
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: api-config-map
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SYSTEM_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: auth-key
      initContainers:
      - name: init-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup postgres-cluster-ip-service; do echo waiting for postgres; sleep 2; done"]